name: dotnet-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
    - name: install dotnet-exec
      run: dotnet tool install -g dotnet-execute
    - name: build
      run: dotnet build Skoruba.IdentityServer4.Admin.sln
    - name: test
      run: dotnet test ./tests/Skoruba.IdentityServer4.Admin.UnitTests/Skoruba.IdentityServer4.Admin.UnitTests.csproj
